### ISSUE TITLE
EigensolverBandToTridiagTest deadlock with stdexec

### ISSUE THREAD

**Issue by rasolca** [eth-cscs/DLA-Future#1059]
See #1018 failure:

Twice in a row:
https://gitlab.com/cscs-ci/ci-testing/webhook-ci/mirrors/4700071344751697/7514005670787789/-/jobs/5382755056

https://gitlab.com/cscs-ci/ci-testing/webhook-ci/mirrors/4700071344751697/7514005670787789/-/jobs/5380073800

**Comment by msimberg** [comment]
I suspect this is the same issue as https://github.com/eth-cscs/DLA-Future/pull/1004 is trying to fix.

**Comment by msimberg** [comment]
Closing this tentatively since #1004 is merged. Let's reopen if it seems like issues remain.
