### ISSUE TITLE
Slowness of MPI+HPX tests

### ISSUE THREAD

**Issue by albestro** [eth-cscs/DLA-Future#106]
There is a slowdown on tests based on MPI and HPX.

**Comment by albestro** [comment]
Speculation is that it may be related to the fact that all ranks run on the same node and are bound to the same core. If this happens, all processes will try to use exactly the same core, and this concurrent scheme would lead to delays.

It should be investigated if this is the problem. In case, the HPX flag `--hpx:use-process-mask` might be useful if the workload manager (e.g. slurm) assigns different cores to each rank of the same node.

**Comment by rasolca** [comment]
I confirm this hypothesis:
```
/usr/bin/srun "-n" "6" "/users/jenkssl/workspace/ssl_DLA-Future_PR-109/build_Release/test/unit/test_matrix" --hpx:print-bind
```
all the ranks reports:
```
   0: PU L#0(P#0), Core L#0(P#0), Socket L#0(P#0), on pool "default"
   1: PU L#2(P#1), Core L#1(P#1), Socket L#0(P#0), on pool "default"
   2: PU L#4(P#2), Core L#2(P#2), Socket L#0(P#0), on pool "default"
   3: PU L#6(P#3), Core L#3(P#3), Socket L#0(P#0), on pool "default"
   4: PU L#8(P#4), Core L#4(P#4), Socket L#0(P#0), on pool "default"
   5: PU L#10(P#5), Core L#5(P#8), Socket L#0(P#0), on pool "default"
   6: PU L#12(P#6), Core L#6(P#9), Socket L#0(P#0), on pool "default"
   7: PU L#14(P#7), Core L#7(P#10), Socket L#0(P#0), on pool "default"
   8: PU L#16(P#8), Core L#8(P#11), Socket L#0(P#0), on pool "default"
   9: PU L#18(P#9), Core L#9(P#16), Socket L#0(P#0), on pool "default"
  10: PU L#20(P#10), Core L#10(P#17), Socket L#0(P#0), on pool "default"
  11: PU L#22(P#11), Core L#11(P#18), Socket L#0(P#0), on pool "default"
```
and the test_matrix time is:
```
[==========] 91 tests from 9 test suites ran. (14564 ms total)
```
On the other hand (NOTE: **same** executable) with
```
/usr/bin/srun "-n" "6" -c 12 "/users/jenkssl/workspace/ssl_DLA-Future_PR-109/build_Release/test/unit/test_matrix" --hpx:print-bind --hpx:use-process-mask
```
The ranks report:
```
   0: PU L#0(P#0), Core L#0(P#0), Socket L#0(P#0), on pool "default"
   1: PU L#2(P#1), Core L#1(P#1), Socket L#0(P#0), on pool "default"
   2: PU L#4(P#2), Core L#2(P#2), Socket L#0(P#0), on pool "default"
   3: PU L#6(P#3), Core L#3(P#3), Socket L#0(P#0), on pool "default"
   4: PU L#8(P#4), Core L#4(P#4), Socket L#0(P#0), on pool "default"
   5: PU L#10(P#5), Core L#5(P#8), Socket L#0(P#0), on pool "default"
*******************************************************************************
   0: PU L#36(P#18), Core L#18(P#0), Socket L#1(P#1), on pool "default"
   1: PU L#38(P#19), Core L#19(P#1), Socket L#1(P#1), on pool "default"
   2: PU L#40(P#20), Core L#20(P#2), Socket L#1(P#1), on pool "default"
   3: PU L#42(P#21), Core L#21(P#3), Socket L#1(P#1), on pool "default"
   4: PU L#44(P#22), Core L#22(P#4), Socket L#1(P#1), on pool "default"
   5: PU L#46(P#23), Core L#23(P#8), Socket L#1(P#1), on pool "default"
*******************************************************************************
   0: PU L#12(P#6), Core L#6(P#9), Socket L#0(P#0), on pool "default"
   1: PU L#14(P#7), Core L#7(P#10), Socket L#0(P#0), on pool "default"
   2: PU L#16(P#8), Core L#8(P#11), Socket L#0(P#0), on pool "default"
   3: PU L#18(P#9), Core L#9(P#16), Socket L#0(P#0), on pool "default"
   4: PU L#20(P#10), Core L#10(P#17), Socket L#0(P#0), on pool "default"
   5: PU L#22(P#11), Core L#11(P#18), Socket L#0(P#0), on pool "default"
*******************************************************************************
   0: PU L#48(P#24), Core L#24(P#9), Socket L#1(P#1), on pool "default"
   1: PU L#50(P#25), Core L#25(P#10), Socket L#1(P#1), on pool "default"
   2: PU L#52(P#26), Core L#26(P#11), Socket L#1(P#1), on pool "default"
   3: PU L#54(P#27), Core L#27(P#16), Socket L#1(P#1), on pool "default"
   4: PU L#56(P#28), Core L#28(P#17), Socket L#1(P#1), on pool "default"
   5: PU L#58(P#29), Core L#29(P#18), Socket L#1(P#1), on pool "default"
*******************************************************************************
   0: PU L#24(P#12), Core L#12(P#19), Socket L#0(P#0), on pool "default"
   1: PU L#26(P#13), Core L#13(P#20), Socket L#0(P#0), on pool "default"
   2: PU L#28(P#14), Core L#14(P#24), Socket L#0(P#0), on pool "default"
   3: PU L#30(P#15), Core L#15(P#25), Socket L#0(P#0), on pool "default"
   4: PU L#32(P#16), Core L#16(P#26), Socket L#0(P#0), on pool "default"
   5: PU L#34(P#17), Core L#17(P#27), Socket L#0(P#0), on pool "default"
*******************************************************************************
   0: PU L#60(P#30), Core L#30(P#19), Socket L#1(P#1), on pool "default"
   1: PU L#62(P#31), Core L#31(P#20), Socket L#1(P#1), on pool "default"
   2: PU L#64(P#32), Core L#32(P#24), Socket L#1(P#1), on pool "default"
   3: PU L#66(P#33), Core L#33(P#25), Socket L#1(P#1), on pool "default"
   4: PU L#68(P#34), Core L#34(P#26), Socket L#1(P#1), on pool "default"
   5: PU L#70(P#35), Core L#35(P#27), Socket L#1(P#1), on pool "default"
```
and the time is:
```
[==========] 91 tests from 9 test suites ran. (109 ms total)
```

**Comment by albestro** [comment]
MPI+HPX tests need the additional parameter `--hpx:use-process-mask`, that can be easily added in `DLAF_AddTest`.

The relationship between MPI and HPX exists when binding of CPU resources is specified. In this case coordination between parameters for MPI, in case it does the binding (e.g. by means of a workload manager), and HPX is required.

### Variables
These would be the additional variables:

- `MPIEXEC_NUMCORE_FLAG`:		(default=""	optional) e.g. "-c"
- `MPIEXEC_NUMCORES`:			(default=1	optional) e.g. 36
- `DLAF_HPXTEST_EXTRA_ARGS`:	(default=""	optional) e.g. "" or "--hpx:print-bind"

The latter one is just a helper variable, that allows specifying an additional string to pass to each HPX based test.

**CONSTRAINT** `MPIEXEC_NUMCORES` and `MPIEXEC_NUMCORE_FLAG` must be either both sets or both empty.

### Presets
In particular, we would provide a few presets to help the user, but leaving the option to customize the configuration.

These are the presets:

- **PLAIN_MPI**
	`MPIEXEC_EXECUTABLE`: `<unchanged>`
	`MPIEXEC_NUMPROC_FLAG`: `<unchanged>`
	`MPIEXEC_NUMCORE_FLAG`: `<unchanged>`

- **SLURM**
	`MPIEXEC_EXECUTABLE`: `which srun`
	`MPIEXEC_NUMPROC_FLAG`: "-n"
	`MPIEXEC_NUMCORE_FLAG`: "-c"

	`MPIEXEC_NUMCORES`: `<must be set by the user>`

- **CUSTOM**
	`MPIEXEC_EXECUTABLE`: `<can be set by the user>`
	`MPIEXEC_NUMPROC_FLAG`: `<can be set by the user>`
	`MPIEXEC_NUMCORE_FLAG`: `<can be set by the user>`
	`MPIEXEC_NUMCORES`: `<can be set by the user>`

### Usage
Previous variables will be used by CMake to set the right command line arguments.
In particular:

- `DLAF_AddTest` will add `--hpx:use-process-mask` for HPX and MPIHPX tests
- `DLAF_AddTest` will add `${DLAF_HPXTEST_EXTRA_ARGS}` for HPX and MPIHPX tests
- if `MPIEXEC_NUMCORE_FLAG` is set, the test will be called with a command like (where `CORES_PER_RANK = max(1, MPIEXEC_NUMCORES / NUM_MPIRANKS)`)
```
${MPIEXEC_EXECUTABLE} ${MPIEXEC_NUMPROC_FLAG} ${NUM_MPIRANKS} ${MPIEXEC_NUMCORE_FLAG} ${CORES_PER_RANK} <test-name>
```

**Comment by albestro** [comment]
@rasolca @teonnik 

What do you think about the previous comment?

**Comment by teonnik** [comment]
Looks good to me!
