### ISSUE TITLE
Add environment variable to print configuration

### ISSUE THREAD

**Issue by msimberg** [eth-cscs/DLA-Future#1186]
We currently have the command line option `--dlaf:print-config` which dumps the configuration used by DLA-Future. Is there any opposition to adding a corresponding `DLAF_PRINT_CONFIG` environment variable (or similar, but I think this name makes most sense given the existing command line option) with the same effect, that could be used e.g. when running CP2K?

**Comment by rasolca** [comment]
No opposition.
