### ISSUE TITLE
Library deployment does not work

### ISSUE THREAD

**Issue by albestro** [eth-cscs/DLA-Future#157]
I tried to install the library and use it from another CMake project and it does not work.

The first problem is on the dependency MKL, but it is not the only problem.

I'm going to update the problems I address in the comments below.

**Comment by albestro** [comment]
Reverting to the old MKL script, the MKL problem is solved. I have to investigate further in order to fix the current one and eventually I will update the repo from where we took it.

With this workaround another problem of missing dependencies arose, specifically `blaspp`, `lapackpp` and `OpenMP`.

I'm going to open a PR with these fixes, but I will continue to work trying to fix also the MKL CMake find-package.

**Comment by albestro** [comment]
@rasolca 

I think we should force the `c++14` standard also on dependent libraries. What do you think?

**Comment by rasolca** [comment]
Do you mean c++14 or >= c++14?

**Comment by albestro** [comment]
I take it as a hint 😁
