### ISSUE TITLE
Benchmark: Cholesky factorization mini-app (pre)

### ISSUE THREAD

**Issue by albestro** [eth-cscs/DLA-Future#164]
We want to collect some preliminary results about performances of the current state of the Cholesky factorization mini-app (branch `miniapp_cholesky_random`).

It is mainly a check that we are on the right track compared to the prototype results.

The purpose of this issue is to decide and specify how the benchmark will be carried out.

ToDo & Topics:
- [x] Define configurations
- [x] Define command line
- [x] Is MPI pool enabled?
- [ ] Column vs Tile layout?
- [x] Recover build options for best HPX performances

**Comment by albestro** [comment]
### Configurations
- matrix_size: [10240, 20480, 40960]
- block_size: [512]
- nodes: [1,2,4,8,16,32,64,96,128,192,256]

1 task per node
36 cores per task

Questions:
- [ ] block_size 256?

### Command Line
```bash
srun
-n ${nodes}
-c 36
miniapp_cholesky
--matrix-size {matrix_size}
--block-size {block_size}
--grid-rows {r}
--grid-cols {c}
--nruns 6
--check-result
--hpx:use_process_mask
```

Questions:
- [ ] Hyperthreading?
- [ ] Grid Size? Squarest one with priority on rows? Test all combinations?

**Comment by albestro** [comment]
### HPX Build

I recovered a note that I took a few months ago talking with @biddisco about building HPX for the best performance.

```
# If you want to benchmark an application,
# it would be worth disabling some extra things
# (some features will be disabled, e.g. hpx::cout)

-DHPX_WITH_NETWORKING:BOOL=OFF
-DHPX_WITH_LOGGING:BOOL=OFF
-DHPX_WITH_IO_COUNTERS:BOOL=OFF
-DHPX_WITH_PARCELPORT_ACTION_COUNTERS:BOOL=OFF
-DHPX_WITH_PARCEL_PROFILING:BOOL=OFF
-DHPX_WITH_STACKTRACES:BOOL=OFF
-DHPX_WITH_THREAD_CUMULATIVE_COUNTS:BOOL=OFF
-DHPX_WITH_THREAD_IDLE_RATES:BOOL=OFF
-DHPX_WITH_THREAD_MANAGER_IDLE_BACKOFF:BOOL=OFF
-DHPX_WITH_THREAD_STEALING_COUNTS:BOOL=OFF
-DHPX_WITH_VERIFY_LOCKS:BOOL=OFF
-DHPX_WITH_TIMER_POOL:BOOL=OFF
-DHPX_WITH_IO_POOL:BOOL=OFF
```

**Comment by albestro** [comment]
### Matrix Memory Layout

At the moment the mini-app uses the default layout of the `Matrix`, i.e. column-major layout, without an option, at build or runtime, to select the memory layout.

Do we want to test both layouts?

**Comment by rasolca** [comment]
I would go for:
- nb = 256 and 512
- rank per nodes 1 and 2
- square grids if possible maybe check if it is better more cols or more rows for the non square cases...

moreover go for `-c72` for 1 rank per node and `-c36` for 2 ranks (HPX balanced mode avoid to place threads on hyperthreads.) otherwise slurm may produce wrong bindings.

**Comment by albestro** [comment]
I collected the first benchmarks results with the configuration we talked about. At the moment I have results just for the column layout.

@rasolca do we want to run also with tile layout?

**Comment by albestro** [comment]
Reporting some results from this first round of benchmarks.

Next plots show the results for:
- matrix stored in memory with column layout;
- ranks structured in the more square 2D grid possible
- each average point is obtained by running at least 3 times a set of 5 runs; so, excluding the 0-run, each statistic is computed over at least 12 samples

Moreover, a very brief description of what it is depicted:
- blue and orange lines are for the **average performance** among runs, excluded the "0"-run; they are respectively for configurations with 1 and 2 ranks per node.
- for each point on previous lines, there are two triangular markers indicating **max** and **min** performance (always 0-run excluded), respectively pointing up and down.

![image](https://user-images.githubusercontent.com/9337627/77541918-af6c7000-6ea5-11ea-849f-59dc25d88f7c.png)

![image](https://user-images.githubusercontent.com/9337627/77541927-b2fff700-6ea5-11ea-8cc1-b056d01012db.png)
