### ISSUE TITLE
MPI Cartesian topology

### ISSUE THREAD

**Issue by teonnik** [eth-cscs/DLA-Future#168]
Currently, the CommunicationGrid class does not utilize MPI's Cartesian topology feature (MPI_Cart_create and friends). Are we interested in a PR that utilizes the feature?

**Comment by albestro** [comment]
We talked about this with @rasolca when I was implementing the `CommunicatorGrid`, but I cannot recall the exact reason.

Maybe @rasolca can give you more details.
