### ISSUE TITLE
Implement Communicators 1D and 2D

### ISSUE THREAD

**Issue by rasolca** [eth-cscs/DLA-Future#17]
Design and implement communicators.

The prototype interface is basic and should be redesigned.

To create the row and column communicators it is better to use `MPI_Comm_split`. See `misc/code.(pdf|pptx)`

**Comment by albestro** [comment]
Talking with @rasolca, there are additional requirements:

- Communicator2D should be implemented using MPI_Comm_split (from slides)
- Provide a way to duplicate Communicator
