### ISSUE TITLE
dlaf::comm::mpi_datatype changes introduced a warning (note) on clang comipler

### ISSUE THREAD

**Issue by albestro** [eth-cscs/DLA-Future#173]
The changes of `mpi_datatype` introduced in #170 addressed the compatibility problem with OpenMPI (_"MPI_Datatype is not guaranteed to be constexpr"_) and contextually moved all the template specializations to another translation unit.

This triggers a warning on clang (`Apple LLVM version 10.0.1 (clang-1001.0.46.4)`) that suggests to explicit the declaration if it is explicitly instantiated in another translation unit (as it is now for us).

```bash
include/dlaf/communication/message.h:41:52: note: add an explicit instantiation declaration to suppress this warning if
      'dlaf::comm::mpi_datatype<int>::type' is explicitly instantiated in another translation unit
      classic_type_ = dlaf::comm::mpi_datatype<T>::type;
```

**Comment by albestro** [comment]
I completely agree with moving the template specializations away from the header, but I would go for something like having an header that explicitly tells what it is already available in the other translation unit.

A first proposal may be something like

```cpp
// include/internal/datatypes.h

template <typename T>
struct mpi_datatype {
  static MPI_Datatype type;
};
```

```cpp
// src/communication/datatypes.cpp

#include "dlaf/communication/internal/idatatypes.h"

template <>
MPI_Datatype mpi_datatype<char>::type = MPI_CHAR;

```

```cpp
// include/datatypes.h

#include "internal/datatypes.h"

extern template MPI_Datatype mpi_datatype<double>::type;
```

And then use the `datatypes.h` in the code.

What do you think about this @teonnik?

**Comment by teonnik** [comment]
This looks like a good solution. Unfortunately, I am not able to test it myself, as I haven't gotten Clang to work just yet.
