### ISSUE TITLE
Add CI test for both 32bit and 64bit integer interfaces (SizeType)

### ISSUE THREAD

**Issue by albestro** [eth-cscs/DLA-Future#189]
It may be worth adding CI tests for both integer interfaces.

This would require adding a CMake option which controls if `SizeType` is `int32_t` or `int64_t`.

This issue started from https://github.com/eth-cscs/DLA-Future/pull/185#issuecomment-613985256

**Comment by rasolca** [comment]
As SizeType is required to be 64 bits after #247, there's no need for it.
