### ISSUE TITLE
Build problem on GCC 7.4.0

### ISSUE THREAD

**Issue by albestro** [eth-cscs/DLA-Future#200]
`DLAF_ASSERT*` mechanisms use variadic macro.

They are intended to support also empty messages, so with an empty variadic macro, but this is a compiler extensions.

This extension is used also in GoogleTest, and we already had to disable warnings for Clang compilers with `-Wno-gnu-zero-variadic-macro-arguments`

https://github.com/eth-cscs/DLA-Future/blob/2af76f28e3e6974feec33d7c4c020f8826afbe9a/cmake/DLAF_AddTargetWarnings.cmake#L46-L50

The problem with GCC compiler is the different management of the `-pedantic-errors` flag, since it behaves differently between versions (see https://godbolt.org/z/YDev65).

**Comment by albestro** [comment]
This problem shows up also in our CI with `bors try` which uses `GCC 7.5.0`

**Comment by albestro** [comment]
From C++14 standard N3797 [16.3/4]
> [...] there shall be more arguments in the invocation than there are parameters in the macro definition (excluding the ...).

And the `-pedantic` option description is:
> Issue all the warnings demanded by strict ISO C and ISO C++; reject all programs that use forbidden extensions, and some other programs that do not follow ISO and ISO C++.  For ISO C, follows the version of the ISO C standard specified by any -std option used.

IMHO, the error should be raised also by newer version of GCC.

I see two options:
- remove the `-pedantic` flag, but check if it implies any check that we need and add it back manually;
- keep the `-pedantic`, but we have to find a solution for "variadic macro" overload (not allowing it, or do some macro trick to allow it)

@rasolca @teonnik  What do you think about this?

**Comment by teonnik** [comment]
My preferred approach would be to subsume one of the required parameters (e.g. `condition`) within the variadic macro so that we avoid the whole empty variadic macro issue.

**Comment by rasolca** [comment]
I agree with @teonnik. We should follow the standard to avoid future trouble with other compilers.
