### ISSUE TITLE
Testing the spack package

### ISSUE THREAD

**Issue by albestro** [eth-cscs/DLA-Future#259]
I started exploring and experimenting a bit with `spack` and `docker`.

What I achieved for the moment is:
- with `spack/ubuntu-bionic` official docker image as base
- create a custom docker image that adds the custom dlaf spack repository
- create a spack environment for dla-future (required by `spack containerize`)
- modify the container script generated by `spack containerize`
  - use custom base image (the one with the `dlaf` spack repo)
  - enable/disable stripping (e.g. for debug/release builds, in other contexts would be interesting)
- build the docker image (multi-stage build)

There are still a few downsides at the moment, the firsts I see:
- custom base docker image in spack is still under review (https://github.com/spack/spack/pull/15028)
- the docker image builds everything from source code, e.g. cmake, python, tar, ... (it takes very very long)

What we should target is some kind of cache, being it using docker or spack one (e.g. buildcaches, binary mirrors).

I know that @haampie started exploring this part, and he also did some preliminary feasibility test about a spack mirror.

I think this can be a preliminary work towards creating a spack-based CI/CD also for testing different configurations.

**Comment by haampie** [comment]
> I know that @haampie started exploring this part, and he also did some preliminary feasibility test about a spack mirror.

So far it seems it can work quite nicely with a few patches to spack. You can make spack generate a gitlab pipeline with a base image of your choice. It will generate 1 job for all packages in your environment, you can specify where you want them to be built, and it will do that if they are not yet cached in the binary mirror/cache. Currently I specify that they should be built on daint using sarus, which just works!

Current issues are: there's a lot of overhead to starting a job (salloc/srun, git clone, downloading dependent binaries etc). This can be improved partly by doing an allocation upfront and deallocating afterwards. Another 'problem' is spack does not check in advance whether binaries already exist, so it will always generate an enormous pipeline where most jobs are redundant (binaries are already available, there's nothing to build).

**Comment by albestro** [comment]
@rasolca aren't we implicitly testing spack package with the last changes you did in CI?

**Comment by rasolca** [comment]
Yes, we are.
