### ISSUE TITLE
Test of master didn't run

### ISSUE THREAD

**Issue by rasolca** [eth-cscs/DLA-Future#274]
After merging #245 the test didn't run on master.

Let us see if after merging #273 the tests run.

@haampie any idea on what could have happened?

**Comment by haampie** [comment]
Weird... I don't immediately know. Seems like gitlab decided just not to run it :|.

You can also start using `bors merge` instead of `bors try + manual merge`, that's one way to ensure that master is always green

**Comment by rasolca** [comment]
After #273 the test run correctly.
We will continue to monitor it and see if it happens again.

**Comment by rasolca** [comment]
I close this issue, since all the changes of master have been tested
