### ISSUE TITLE
Backend instances and DLAF initialization/finalization

### ISSUE THREAD

**Issue by msimberg** [eth-cscs/DLA-Future#306]
#234 means that there will be a need for potentially static data for different backends to avoid having each algorithm invocation set up resources separately.

I see two main approaches:
- `dlaf::initialize/finalize` together with backend specific accessors or instances, and static data backing these up.
- backend structs, that the user is responsible for and algorithms taking an instance of a backend rather than just a template parameter.

For the first approach I imagine either something like `dlaf::makeHighPriorityExecutor<Backend::GPU>` or `dlaf::cublas::Executor(dlaf::GPU().getHandlePool())` being possible. In both cases the static data (i.e. streams and handles) have been set up by a call to `dlaf::initialize`. The `initialize/finalize` calls can of course also be hidden in an RAII object.

The second approach would leave the responsibility of lifetimes to the user, but would be less "magic". In executables I'd expect to see `dlaf::GPU backend;`, or `dlaf::GPU backend(argc, argv);`, or even `dlaf::DefaultBackend backend(argc, argv);` which would then get passed into `dlaf::triangular_solver(backend, ...)`.

Finally, both `Backend` and `Device` are very close to Kokkos execution and memory spaces. Is using Kokkos something that you would consider, or is that out of the question (even if the API need not expose Kokkos at all)?

**Comment by rasolca** [comment]
I think that first approach is better.
Regarding Kokkos I would not exclude it a priory. If it is helpful why not use it?

**Comment by msimberg** [comment]
Apologies to @albestro. I just discovered #100, which largely concerns the same topic as here. Do we want to keep both open, or continue the discussion only in one of these issues?

**Comment by albestro** [comment]
There's not so much discussion yet on the other one. I think we can close #100 and continue here. 😉

**Comment by msimberg** [comment]
I'm going to close this since #312 was merged.
