### ISSUE TITLE
Scripts for benchmark analysis

### ISSUE THREAD

**Issue by albestro** [eth-cscs/DLA-Future#311]
In the past year we have created a set of python scripts for analysis of benchmark results.

It has been recognized to be helpful for the entire team, especially for evaluating new features. So the time has come to share our efforts on improving and fixing these scripts too.

Do we want to provide them as part of our library (e.g. in tools, in miniapp, ...)? Or do we want to keep them in a private team git repo?

Looking forward to your proposals.

**Comment by msimberg** [comment]
I'm in support of simply having them in the scripts subdirectory.

**Comment by Sely85** [comment]
I think that such scripts can be useful for users too. 
I agree that the scripts subdirectory would be a good location.

**Comment by albestro** [comment]
> I think that such scripts can be useful for users too.
> I agree that the scripts subdirectory would be a good location.

What do you have in mind about "being useful for users"?

**Comment by Sely85** [comment]
If we provide them

> > I think that such scripts can be useful for users too.
> > I agree that the scripts subdirectory would be a good location.
> 
> What do you have in mind about "being useful for users"?

Not sure I've understood correctly.
But besides the fact that these scripts are a great tool for us when developing new features, I think that users approaching a new library would probably make some benchmarks on their own clusters as well. And if we are able to provide "tools" (aka scripts working on our cluster) for analyzing benchmarks results quickly it might be useful.

**Comment by teonnik** [comment]
My concern is that we all have different workflows and may need/want to change the scripts considerably. However, I do agree that having a starting point is very useful, that is what I would potentially use the scripts for. 

I prefer having them in the scripts directory. It's less of a hassle than managing multiple repositories. I would also prefer if they are python / bash scripts and not jupyter notebooks. Notebooks can be converted to scripts and vice-versa:

```bash
jupyter nbconvert  foo.ipynb --to="python" --output="foo.py"
```  

How do we decide whose scripts we upload?

**Comment by rasolca** [comment]
> My concern is that we all have different workflows and may need/want to change the scripts considerably. However, I do agree that having a starting point is very useful, that is what I would potentially use the scripts for.

I have the same concern as @teonnik. The scripts can vary a lot depending on the benchmark.
How we would deal with it? If we just upload a basic version, we risk to increase the effort of maintaining the personal variations.

> I prefer having them in the scripts directory. It's less of a hassle than managing multiple repositories.

Fine with me.

> I would also prefer if they are python / bash scripts and not jupyter notebook.

I don't know how the scripts are currently structured, but I would suggest to have some common python modules, and an example notebook to show how to use them (which includes a sample output).
 
> How do we decide whose scripts we upload?

No preference for me.

**Comment by msimberg** [comment]
@teonnik are your scripts a (roughly) superset of @albestro's original scripts? If yes, I suggest we just go with that. I'm at least happy to adapt to your structure (I can always keep the old scripts around for old benchmarks).

**Comment by albestro** [comment]
> > My concern is that we all have different workflows and may need/want to change the scripts considerably. However, I do agree that having a starting point is very useful, that is what I would potentially use the scripts for.
> 
> I have the same concern as @teonnik. The scripts can vary a lot depending on the benchmark.
> How we would deal with it? If we just upload a basic version, we risk to increase the effort of maintaining the personal variations.

The pipeline I see is:
- GENERATE: generate the bash scripts. I was doing it "manually" by altering a template, but @teonnik worked on a nice alternative
- PARSE: once all results are produced, load them in a db (e.g. pandas DataFrame)
- ANALYSIS: produce plots; this is what changes a lot, and I think the only efforts we can do is providing a "canvas" with the classic plot "GFlops/node" and then it is up to the scientist to duplicate/edit for their needs)

My idea was to agree on basic common things and the scripts would provide a way to specialize the parser for the different miniapp (and its variants in different libraries).
For example, by agreeing on the folder structure and on the basic parser grammar, I created a "general" python module that allowed to load a folder of results, by calling a parser function provided by the user. This parser, which differs from library to library and from miniapp to miniapp, has to be defined "each time". I'm going to upload a branch with my very basic stuff, so it is easier also to pick up code and eventually discuss about it.

**Comment by albestro** [comment]
@teonnik Can we close this, right?
