### ISSUE TITLE
Matrix read/write access function naming

### ISSUE THREAD

**Issue by msimberg** [eth-cscs/DLA-Future#340]
Currently matrices can be indexed as follows:

- read-only: `read`
- read-write: `operator()`

My preference is to make the read/write version more explicit, especially considering it's more expensive (gives exclusive access to a tile). On the other hand, read/write access is *probably* the most common type of access and `operator()` gives succinct access to such tiles.

I'm going to list in no particular order some potential alternatives. I think the DLA-Future developers can all give their preference, but if any change is going to happen we should first check with potential future users what their preference is. I've stated before that this is not a huge deal for me, so let's not turn this into unnecessary bike-shedding. If we can't find consensus on a better alternative the status quo is good enough.

| variant # | read-only | write-read |
| --- | --- | --- |
| 1 | `read` | `operator()` |
| 2 | `read` | `operator[]` |
| 3 | `operator()` | `write` |
| 4 | `operator[]` | `write` |
| 5 | `read` | `write` |
| 6 | `r` | `w` |
| 7 | `r` | `rw` |

Alternatives to `write`: `read_write`, `rw`, `w`, `mut`, `get`, `get_mutable`. Alternatives to `read`: `r`, `cget`, `get_const`. Please expand the table if you have other ideas.

And finally, my preference is the explicit `read`/`write` pair (5). I think any brevity gained by `operator()` is offset by the clarity of explicit names.

**Comment by Sely85** [comment]
Just my two cents. I would also go for a more explicit version: variant #5 would be a good choice in my opinion. Probably using `read_write`, instead of `write`, would make it even clearer, to new users too. 
By the way, I have now been using variant #1 for a while and it would fine to continue using it as well.

**Comment by albestro** [comment]
> And finally, my preference is the explicit read/write pair (5). I think any brevity gained by operator() is offset by the clarity of explicit names.

I agree with you, in case there will be a decision about renaming, solution (5) may be in the right direction.

**Comment by msimberg** [comment]
Agreed in meeting to go ahead with `read` and `readwrite` (or does someone want `read_write`?). I will change this in #766.
