### ISSUE TITLE
clang-format headers order

### ISSUE THREAD

**Issue by rasolca** [eth-cscs/DLA-Future#42]
Currently clang-format format headers according to the coding style:
- if the main header is in a separated block (no way to fix it, but already mentioned in the coding style)
- if C and C++ standard headers are included using `<>`
- if third party libraries and DLAF headers are included with `""`.

The coding style do not mention any restriction on `<>` or `""`

Question:
Should we restrict it? At what level?

IMHO we should restrict C and C++ to `<>` and DLAF to `""`, but I'm not sure about third party libs.

**Comment by teonnik** [comment]
The following is an interesting read: https://build2.org/build2-toolchain/doc/build2-toolchain-intro.xhtml#proj-struct . It suggests (among other things) using `<>` for everything.
