### ISSUE TITLE
MPI "pretty" printer for GTest

### ISSUE THREAD

**Issue by albestro** [eth-cscs/DLA-Future#50]
The output of MPI-based tests is not readable since there are multiple processes printing on the same shared console.

Add an output manager for DLAF_gtest_mpi_main.

**Comment by albestro** [comment]
@rasolca 

I started implementing in branch [mpi_pretty_printer](https://github.com/eth-cscs/DLA-Future/tree/mpi_pretty_printer) the skeleton for solving this issue. I didn't test it extensively and I don't know if it covers sufficiently the cases domain.

I worked to collect all the information from failures/passed and a lot less on the "prettiness" of the output, so I'm willing to get suggestions on how to prettify it (but not only).

This is the status at the time of writing 317f04e...d88fb03

**Comment by rasolca** [comment]
I would use the same format as `PrettyUnitTestResultPrinter` (which is the one used as default).
