### ISSUE TITLE
Refactor dispatching to CPU and GPU in the tridiagonal eigensolver

### ISSUE THREAD

**Issue by teonnik** [eth-cscs/DLA-Future#634]
Currently most kernels are dispatched using an expression of the form:

```
auto kernel_f = [] (/*some parameters*/, [[maybe_unused]] auto&&... ts) {
  if constexpr (D == Device::CPU) {
     // CPU code
  } else {
     // ts... is usually cudaStream_t
     // GPU code
  }
}

transformDetach(Policy<DefaultBackend<D>::value>(), std::move(kernel_f), std::move(sender));

```

Instead, it would be cleaner to have helper functions for the CPU and GPU cases and then use the various macros to create all the needed overloads such that we can use an expression of the form:

```
   start_detached(sender | some_kernel(Policy<B>{})));
```

**Comment by rasolca** [comment]
Please add this suggestion to the API refactoring page.
