### ISSUE TITLE
Custom findpackage modules should be namespaced to DLA-Future

### ISSUE THREAD

**Issue by msimberg** [eth-cscs/DLA-Future#641]
Reported by @mtaillefumier:
```
CMake Error at /gpfs/alpine/gen010/proj-shared/dft-codes/summit/lib64/cmake/DLAF/FindLAPACK.cmake:79 (target_link_libraries):
   target_link_libraries can not be used on an ALIAS target.
```
which results from a conflict between the `FindLapack.cmake` module in CP2K (https://github.com/mtaillefumier/cp2k/blob/fbea0ebc32f2c8f92b54ac2028b2dbbf56351bfc/cmake/FindLapack.cmake#L136) and the `FindLAPACK.cmake` module in DLA-Future (https://github.com/eth-cscs/DLA-Future/blob/0037c966aec1a2b6cbf99e9a68b8cbb1b572dd1c/cmake/FindLAPACK.cmake#L76).

Ignoring the issue whether compatible blas implementations are found [1], using `DLAF::lapack` (or `DLAFInternal::` or anything prefixed with `DLAF`) instead for the target name avoids conflicts (because if some other package creates a target prefixed with `DLAF::` they are being very bad).

We have an issue for this in pika as well, but have been lazy at fixing the remaining packages: https://github.com/pika-org/pika/issues/9.

[1] This may deserve its own issue. Is https://cmake.org/cmake/help/latest/module/FindLAPACK.html not useful by the way?

**Comment by rasolca** [comment]
> Ignoring the issue whether compatible blas implementations are found 

Unfortunately this can't be ignored as it can lead to catastrophic performance issues... but I don't see any way to check it.

> [1] This may deserve its own issue. Is https://cmake.org/cmake/help/latest/module/FindLAPACK.html not useful by the way?

Not sure if it has been improved. My past experience with it is that it is good if you are just trying to find a working library, but it is very hard when you want to use specific configurations.

**Comment by msimberg** [comment]
Only `FindMKL` remains as un-namespaced, but there's a separate issue to update that anyway (https://github.com/eth-cscs/DLA-Future/issues/626), so I'm closing this.
