### ISSUE TITLE
Numerical error in test for Backtransform Tridiagonal to Band

### ISSUE THREAD

**Issue by albestro** [eth-cscs/DLA-Future#643]
Test `test_bt_band_to_tridiag` fails randomly, it can happen after few tens of runs or few hundreds, with a numerical error.

I've seen it failing on GPU, never on MC, both Local and LocalSubBand.

I was able to reproduce it on:
- (current) master 0037c966aec1a2b6cbf99e9a68b8cbb1b572dd1c
- in CI environment with Sarus (manually) running `release-cuda-gcc11/deploy:0e8f3f4169ab0a32aa74951baef9ab4f835a7e07`

CI apparently never triggered it, probably due to the low probability of the event, but in #633 seems to be a bit more frequent (I think it is likely unrelated to the changes I did there).

**Comment by rasolca** [comment]
other occurrences:
https://gitlab.com/cscs-ci/eth-cscs/DLA-Future/-/jobs/3149563286#L2059
https://gitlab.com/cscs-ci/eth-cscs/DLA-Future/-/jobs/3149706825#L1351
