### ISSUE TITLE
Install more dependencies from Ubuntu repositories in CI

### ISSUE THREAD

**Issue by msimberg** [eth-cscs/DLA-Future#699]
Packages like hwloc, ninja, libxml, pkgconf, etc. should have little to no impact on DLA-Future or pika behaviour and could be installed from Ubuntu's repositories to slightly speed up rebuilds of the CI images (only helps when rebuilding the base image).

**Comment by rasolca** [comment]
Note:
IIRC when I set the CI up, I choose this path for all negligible impact packages which supported `spack external find`.
Anyway it is good to check if the support improved.
