### ISSUE TITLE
Management of tags for MPI_Isend and MPI_Irecv across and within algorithms

### ISSUE THREAD

**Issue by teonnik** [eth-cscs/DLA-Future#700]
Calls from two or more algorithms or two or more kernels within an algorithm using the same communicator and tags for MPI_Isend and MPI_Irecv may cause MPI messages mismatch. We need a system or convention for managing tags for MPI_Isend and MPI_Irecv calls on the same communicator.

**Comment by rasolca** [comment]
Across algorithms there should be no conflicts, as the communicator should be duplicated (current convention. Anyway a constraint of the new communicator management system is to ensure that a communicator should not be used by two algorithms (or two different executions of the same algorithm) at the same time).

Within an algorithm the tags should be chosen such that they don't overlap. Anyway it is responsibility of the algorithm to define the tags, as its dependencies determine where a tag can be reused safely or not.

**Comment by msimberg** [comment]
This should be closed by #993, no?
