### ISSUE TITLE
Fix segmentation faults for HIP on ault

### ISSUE THREAD

**Issue by aurianer** [eth-cscs/DLA-Future#733]
Tested on ault07 with `--offload-arch=gfx906:xnack-`

Fix segmentation faults appearing in RelWithDebInfoMode:
- test_util_matrix (Failed)
- test_panel (Failed)
- test_band_to_tridiag (Failed)
- test_bt_band_to_tridiag (Timeout)
- test_tridiag_solver_local (SEGFAULT)
- test_eigensolver (Failed)
- test_gen_eigensolver (Failed)
- test_reduction_to_band (Failed)
- test_bt_reduction_to_band (Failed)
- test_gen_to_std (Failed)
- test_tridiag_solver_distributed (Failed)
- test_cholesky (Failed)
- test_compute_t_factor (Failed)
- test_multiplication_triangular (Failed)
- test_permutations_distributed (Failed)
- test_triangular (Failed)

https://gist.github.com/aurianer/8826bbff9f3cf4b606604d85f0984839

Segfaults in Debug mode:
- test_band_to_tridiag (Failed)
- test_bt_band_to_tridiag (Failed)
- test_eigensolver (Failed)
- test_gen_eigensolver (Failed)
- test_reduction_to_band (Failed)
- test_bt_reduction_to_band (Failed)
- test_tridiag_solver_distributed (Failed)
- test_compute_t_factor (Failed)
- test_multiplication_general (Failed)
- test_triangular (Failed)

**Comment by msimberg** [comment]
Related: https://github.com/eth-cscs/DLA-Future/issues/602.

**Comment by msimberg** [comment]
This can possibly be closed based on the results in #747. We at least know that the tests can run successfully on hohgant. It may be a limitation of the hardware on ault or a bad spack environment that was causing the failures in this issue.

**Comment by rasolca** [comment]
I missed this issue...
Solved by #742
