### ISSUE TITLE
AMD CI does not report warnings as errors

### ISSUE THREAD

**Issue by albestro** [eth-cscs/DLA-Future#740]
> I've seen them while building in my VM, but actually if you access the complete raw log of the CI, you can find them 😉
> 
> It seems that warning are enabled but they are not considered errors as for other builds.

When we call cublas/solver rocblas/solver we should make sure that the integer type is correct (as e.g https://github.com/eth-cscs/DLA-Future/blob/master/include/dlaf/blas/tile.h#L392-L404) such that warnings should not be generated.

Moreover the variant `+ci-test` should enable `-Werror`. https://github.com/eth-cscs/DLA-Future/blob/master/spack/packages/dla-future/package.py#L128
Can you please check why it is not the case?

Do you want to fix these problems in this PR or in a new one?

_Originally posted by @rasolca in https://github.com/eth-cscs/DLA-Future/issues/739#issuecomment-1339153660_

**Comment by rasolca** [comment]
I would label it `CMAKE` and not `CI`.... but we don't have the label... 🤣
