### ISSUE TITLE
Revise the content of the misc directory

### ISSUE THREAD

**Issue by rasolca** [eth-cscs/DLA-Future#875]
Some of the content of `/misc` is outdated and it should be updated or removed.

**Comment by rasolca** [comment]
I created a branch `Issue_875` in which I started the cleaning work.

- [ ] @albestro can you please check https://github.com/eth-cscs/DLA-Future/blob/master/misc/compiler-checks.md
- [ ] @msimberg can you please check if https://github.com/eth-cscs/DLA-Future/blob/master/misc/cuda.md is still needed and update it, if we want to keep it?

Note: I'm not planning to touch https://github.com/eth-cscs/DLA-Future/blob/master/misc/matrix_distribution.md yet. The distinction between distribution block and tile size is used only by `RetiledMatrix` and not supported by `Matrix`. I plan to update it when the block size distinction will be available in the Matrix as well and a further update is needed when we work on the deferred tile allocation.

**Comment by msimberg** [comment]
>     * [ ]  @msimberg can you please check if https://github.com/eth-cscs/DLA-Future/blob/master/misc/cuda.md is still needed and update it, if we want to keep it?

I'd say that can be removed. The lifetime considerations are still true, but that's managed by pika so I'm not sure it's worth keeping for that. It's still talking about executors and dataflow which is definitely outdated.
